In [1]:
import pandas as pd
import numpy as np

In [12]:
student_df = pd.read_csv("StudentPerformanceFactors.csv")
student_df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [13]:
student_df.info()
student_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [14]:
print(student_df.columns)

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [15]:
grouped_student = student_df.groupby("Gender")
print("Mean:\n", grouped_student.mean(numeric_only=True))
print("\nMedian:\n", grouped_student.median(numeric_only=True))
print("\nMinimum:\n", grouped_student.min(numeric_only=True))
print("\nMaximum:\n", grouped_student.max(numeric_only=True))
print("\nStandard Deviation:\n", grouped_student.std(numeric_only=True))

Mean:
         Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  \
Gender
Female      20.005013   79.868958     7.041890        75.053348
Male        19.953592   80.056896     7.019664        75.083115

        Tutoring_Sessions  Physical_Activity  Exam_Score
Gender
Female           1.503401           2.961332   67.244898
Male             1.486628           2.972208   67.228894

Median:
         Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  \
Gender
Female           20.0        80.0          7.0             75.0
Male             20.0        80.0          7.0             75.0

        Tutoring_Sessions  Physical_Activity  Exam_Score
Gender
Female                1.0                3.0        67.0
Male                  1.0                3.0        67.0

Minimum:
         Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  \
Gender
Female              1          60            4               50
Male                1          60            4               50

        Tutoring_Sessions  Physical_Activity  Exam_Score
Gender
Female                  0                  0          57
Male                    0                  0          55

Maximum:
         Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  \
Gender
Female             44         100           10              100
Male               39         100           10              100

        Tutoring_Sessions  Physical_Activity  Exam_Score
Gender
Female                  7                  6         101
Male                    8                  6          99

Standard Deviation:
         Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  \
Gender
Female       5.997251   11.629981     1.458610        14.321211
Male         5.986408   11.487558     1.475166        14.458915

        Tutoring_Sessions  Physical_Activity  Exam_Score
Gender
Female           1.233228           1.034821    4.054451
Male             1.228734           1.028706    3.766360

In [19]:
male_attendance = student_df[student_df["Gender"]=="Male"]["Attendance"].tolist()
female_attendance = student_df[student_df["Gender"]=="Female"]["Attendance"].tolist()
print("Male Age List:", male_attendance)
print("Female Age List:", female_attendance)

Male Age List: [84, 98, 89, 88, 84, 78, 94, 98, 80, 97, 83, 82, 78, 60, 75, 99, 78, 62, 83, 66, 70, 69, 72, 65, 68, 63, 94, 98, 70, 86, 77, 71, 68, 86, 88, 94, 91, 65, 88, 78, 98, 66, 86, 75, 73, 96, 100, 77, 72, 61, 69, 71, 78, 95, 88, 63, 86, 86, 60, 97, 97, 91, 64, 69, 67, 92, 79, 98, 67, 99, 100, 73, 77, 72, 71, 60, 84, 86, 88, 73, 70, 97, 78, 78, 66, 77, 78, 87, 85, 96, 61, 65, 92, 92, 75, 64, 64, 86, 77, 76, 87, 63, 84, 91, 93, 67, 96, 95, 79, 97, 71, 76, 76, 71, 71, 94, 87, 67, 62, 71, 91, 95, 79, 79, 95, 91, 81, 60, 76, 90, 82, 81, 74, 81, 89, 94, 78, 87, 70, 86, 77, 96, 100, 64, 61, 66, 100, 94, 71, 94, 71, 87, 87, 69, 61, 72, 92, 78, 84, 93, 71, 71, 81, 78, 68, 78, 81, 66, 95, 76, 61, 80, 82, 67, 70, 92, 65, 66, 88, 84, 63, 77, 71, 81, 84, 99, 79, 73, 80, 90, 80, 89, 92, 87, 94, 88, 95, 73, 69, 76, 89, 69, 71, 67, 90, 70, 75, 99, 76, 84, 84, 77, 62, 81, 64, 68, 70, 98, 94, 69, 68, 61, 87, 81, 96, 92, 65, 82, 98, 65, 74, 66, 94, 86, 79, 64, 87, 62, 77, 65, 65, 91, 70, 79, 87, 77, 65, 68, 76, 94, 74, 88, 83, 63, 65, 73, 76, 74, 89, 98, 62, 83, 97, 62, 83, 94, 70, 95, 61, 97, 86, 78, 97, 61, 88, 65, 69, 85, 77, 83, 86, 97, 87, 97, 83, 78, 73, 92, 88, 89, 88, 64, 71, 93, 66, 75, 97, 91, 90, 85, 82, 99, 89, 91, 69, 79, 93, 78, 62, 85, 93, 84, 67, 99, 69, 87, 84, 86, 78, 76, 97, 72, 95, 91, 97, 83, 74, 86, 94, 84, 94, 71, 81, 78, 82, 84, 89, 83, 63, 77, 82, 73, 89, 86, 73, 90, 86, 85, 98, 93, 84, 74, 79, 99, 64, 89, 77, 74, 72, 80, 83, 63, 62, 93, 62, 79, 72, 81, 65, 100, 77, 74, 93, 78, 64, 94, 73, 99, 70, 78, 76, 98, 81, 82, 62, 73, 83, 98, 94, 68, 97, 91, 79, 65, 95, 77, 75, 90, 74, 79, 90, 66, 76, 99, 69, 80, 88, 81, 95, 72, 63, 97, 75, 83, 92, 73, 89, 72, 92, 89, 81, 78, 73, 84, 98, 94, 79, 86, 77, 84, 88, 98, 90, 81, 71, 73, 76, 68, 98, 80, 76, 74, 82, 80, 65, 80, 67, 65, 97, 84, 86, 86, 91, 75, 98, 93, 94, 63, 68, 69, 83, 60, 77, 76, 88, 89, 60, 98, 93, 61, 97, 92, 93, 64, 90, 98, 87, 83, 84, 79, 97, 87, 98, 63, 76, 81, 96, 94, 65, 64, 84, 81, 96, 97, 76, 75, 79, 78, 75, 61, 64, 80, 88, 88, 88, 97, 78, 68, 62, 85, 70, 72, 73, 70, 67, 91, 87, 85, 92, 72, 71, 72, 72, 81, 87, 75, 89, 73, 72, 61, 77, 98, 64, 94, 84, 93, 76, 82, 82, 83, 98, 96, 95, 92, 98, 71, 80, 94, 70, 67, 74, 71, 64, 92, 75, 89, 95, 85, 77, 67, 90, 68, 74, 92, 88, 91, 89, 75, 68, 85, 99, 72, 78, 82, 62, 100, 90, 95, 64, 74, 95, 68, 92, 93, 94, 87, 81, 93, 71, 81, 83, 68, 62, 76, 95, 60, 83, 81, 96, 78, 82, 89, 75, 60, 60, 80, 61, 87, 72, 82, 72, 67, 76, 81, 68, 64, 63, 84, 81, 82, 76, 98, 71, 77, 93, 68, 88, 72, 72, 69, 67, 64, 79, 73, 85, 66, 68, 94, 70, 75, 95, 74, 87, 61, 89, 79, 93, 80, 74, 79, 95, 68, 97, 93, 64, 92, 60, 75, 80, 62, 86, 79, 80, 98, 69, 89, 82, 97, 75, 79, 82, 81, 63, 68, 79, 89, 81, 73, 98, 96, 64, 100, 98, 75, 94, 77, 91, 61, 74, 73, 64, 66, 61, 79, 98, 65, 98, 89, 85, 64, 80, 83, 63, 81, 80, 93, 76, 64, 62, 73, 89, 90, 69, 65, 98, 74, 80, 75, 70, 61, 67, 86, 91, 93, 80, 89, 99, 94, 88, 98, 68, 63, 90, 75, 84, 62, 75, 88, 87, 68, 97, 61, 78, 61, 73, 65, 75, 87, 91, 81, 71, 66, 69, 68, 82, 71, 62, 88, 91, 78, 88, 66, 98, 63, 61, 73, 93, 82, 72, 75, 93, 78, 94, 82, 69, 92, 91, 69, 89, 67, 60, 78, 74, 82, 94, 67, 89, 91, 89, 65, 66, 90, 79, 91, 61, 72, 86, 60, 61, 94, 87, 88, 72, 97, 74, 64, 91, 69, 70, 100, 68, 97, 66, 99, 98, 69, 85, 90, 99, 67, 91, 74, 77, 79, 82, 76, 85, 76, 88, 98, 82, 64, 68, 80, 61, 81, 71, 83, 97, 97, 91, 68, 87, 85, 99, 70, 98, 88, 78, 74, 90, 68, 79, 81, 67, 100, 65, 61, 70, 72, 65, 76, 75, 99, 83, 79, 82, 73, 66, 94, 97, 92, 88, 60, 77, 96, 67, 71, 81, 71, 68, 64, 62, 75, 77, 75, 97, 62, 87, 96, 92, 67, 72, 89, 63, 89, 89, 87, 93, 61, 75, 66, 97, 94, 67, 61, 64, 84, 65, 68, 77, 95, 64, 78, 100, 93, 60, 72, 79, 95, 98, 62, 60, 86, 72, 70, 80, 80, 70, 90, 69, 79, 82, 80, 64, 99, 98, 78, 93, 85, 74, 84, 72, 96, 73, 61, 93, 93, 98, 76, 73, 67, 84, 79, 95, 61, 86, 91, 90, 95, 89, 73, 61, 70, 64, 70, 61, 96, 60, 66, 96, 96, 86, 60, 99, 86, 96, 72, 97, 66, 69, 82, 91, 85, 90, 99, 92, 78, 96, 81, 91, 81, 83, 69, 66, 80, 97, 92, 85, 71, 78, 62, 99, 84, 82, 86, 61, 89, 69, 75, 93, 75, 84, 70, 99, 88, 69, 67, 71, 61, 88, 80, 64, 90, 61, 96, 89, 63, 93, 87, 100, 85, 78, 86, 83, 61, 97, 91, 91, 76, 70, 71, 62, 77, 69, 96, 93, 82, 79, 74, 80, 66, 81, 70, 67, 63, 91, 77, 85, 89, 75, 86, 95, 67, 65, 85, 72, 96, 69, 72, 92, 67, 61, 85, 99, 73, 83, 96, 91, 85, 73, 82, 64, 87, 89, 99, 61, 82, 68, 73, 69, 79, 71, 88, 62, 76, 97, 60, 84, 80, 87, 87, 62, 76, 78, 75, 77, 99, 64, 93, 74, 76, 75, 97, 64, 64, 66, 81, 87, 79, 99, 95, 94, 96, 65, 96, 69, 96, 72, 99, 88, 69, 68, 82, 70, 68, 70, 77, 69, 80, 95, 88, 64, 67, 91, 70, 77, 74, 83, 66, 96, 81, 80, 83, 85, 95, 98, 95, 75, 84, 96, 100, 81, 93, 91, 92, 94, 96, 68, 65, 99, 95, 96, 86, 80, 80, 67, 71, 84, 66, 92, 72, 98, 93, 88, 77, 84, 73, 91, 94, 94, 94, 66, 86, 79, 96, 75, 80, 78, 74, 90, 94, 99, 71, 89, 76, 87, 79, 100, 93, 96, 70, 61, 81, 96, 66, 77, 74, 92, 81, 83, 65, 77, 62, 70, 88, 70, 60, 70, 60, 69, 81, 84, 77, 89, 71, 65, 82, 73, 78, 86, 80, 82, 90, 88, 81, 87, 77, 83, 61, 64, 84, 90, 91, 96, 72, 83, 83, 80, 64, 69, 62, 88, 94, 77, 84, 85, 96, 99, 96, 65, 93, 100, 79, 82, 73, 63, 96, 92, 66, 91, 85, 70, 88, 82, 84, 64, 79, 68, 76, 86, 90, 95, 66, 74, 76, 65, 67, 72, 85, 96, 81, 82, 75, 75, 98, 78, 90, 71, 98, 63, 96, 94, 87, 75, 77, 78, 83, 79, 62, 95, 78, 66, 60, 70, 88, 64, 69, 68, 67, 61, 91, 85, 68, 79, 70, 89, 72, 63, 68, 95, 92, 99, 89, 75, 78, 67, 99, 85, 82, 65, 98, 90, 99, 71, 68, 70, 87, 80, 76, 78, 85, 75, 94, 90, 91, 79, 68, 69, 95, 95, 78, 61, 77, 86, 66, 67, 88, 69, 92, 85, 74, 84, 79, 77, 60, 72, 90, 98, 97, 60, 74, 74, 74, 64, 74, 93, 63, 98, 99, 64, 72, 75, 84, 86, 90, 88, 83, 88, 68, 77, 80, 98, 61, 97, 94, 81, 65, 70, 83, 96, 86, 79, 94, 79, 95, 65, 94, 83, 96, 98, 80, 75, 85, 92, 71, 88, 65, 84, 98, 64, 63, 99, 62, 90, 81, 75, 83, 78, 64, 97, 75, 81, 62, 71, 93, 63, 64, 74, 84, 63, 72, 84, 86, 84, 76, 79, 60, 68, 96, 63, 80, 84, 73, 90, 69, 95, 68, 91, 68, 68, 85, 72, 73, 74, 87, 69, 100, 67, 94, 76, 67, 66, 83, 68, 76, 98, 87, 90, 78, 89, 78, 88, 84, 74, 69, 62, 87, 86, 79, 74, 97, 88, 70, 83, 81, 66, 84, 73, 62, 86, 87, 74, 81, 98, 70, 97, 76, 88, 78, 83, 79, 93, 61, 71, 60, 89, 92, 98, 84, 91, 88, 88, 75, 89, 75, 67, 65, 92, 100, 67, 89, 90, 64, 94, 93, 62, 73, 80, 71, 75, 62, 76, 93, 85, 89, 96, 82, 86, 79, 73, 93, 71, 91, 74, 92, 81, 72, 86, 86, 68, 83, 95, 78, 90, 68, 85, 89, 93, 78, 91, 72, 73, 87, 83, 96, 88, 91, 98, 69, 61, 87, 79, 74, 94, 84, 75, 72, 67, 87, 87, 73, 81, 62, 94, 89, 88, 98, 82, 84, 99, 86, 61, 96, 92, 87, 100, 71, 86, 66, 71, 93, 80, 98, 76, 84, 96, 97, 91, 61, 75, 86, 93, 77, 87, 78, 63, 76, 97, 77, 77, 88, 98, 71, 78, 92, 67, 81, 78, 71, 69, 95, 79, 74, 94, 89, 96, 73, 98, 61, 96, 71, 71, 72, 84, 78, 87, 97, 71, 66, 64, 83, 65, 72, 84, 93, 90, 70, 60, 74, 88, 73, 82, 89, 62, 78, 65, 69, 77, 68, 82, 65, 61, 66, 88, 63, 80, 98, 91, 78, 98, 84, 83, 98, 73, 78, 93, 67, 73, 67, 94, 76, 76, 67, 75, 75, 98, 98, 95, 60, 84, 92, 65, 64, 97, 91, 77, 90, 75, 89, 99, 74, 97, 97, 70, 77, 97, 90, 69, 68, 84, 88, 79, 62, 92, 70, 73, 82, 78, 95, 83, 76, 77, 63, 64, 77, 81, 81, 64, 79, 79, 80, 80, 72, 82, 78, 77, 67, 85, 61, 76, 72, 95, 87, 62, 69, 77, 88, 73, 93, 84, 76, 82, 67, 76, 74, 76, 90, 79, 72, 77, 91, 82, 82, 62, 76, 100, 72, 95, 87, 74, 82, 94, 95, 66, 74, 73, 66, 88, 61, 63, 83, 90, 64, 94, 63, 65, 76, 96, 80, 84, 93, 77, 80, 98, 82, 67, 89, 65, 77, 70, 95, 71, 60, 90, 71, 63, 91, 66, 86, 97, 87, 92, 70, 89, 87, 77, 62, 91, 73, 65, 69, 86, 93, 92, 75, 92, 74, 61, 96, 70, 99, 61, 97, 63, 62, 90, 79, 77, 97, 96, 89, 73, 75, 85, 85, 76, 99, 93, 77, 89, 71, 74, 61, 93, 74, 63, 67, 96, 84, 100, 94, 100, 92, 91, 61, 73, 66, 61, 69, 72, 81, 69, 80, 98, 79, 62, 86, 83, 70, 73, 97, 64, 80, 64, 74, 85, 98, 84, 88, 76, 63, 88, 70, 65, 95, 83, 76, 68, 90, 88, 68, 72, 78, 86, 72, 99, 62, 65, 81, 94, 89, 69, 80, 92, 94, 96, 88, 64, 62, 60, 69, 99, 65, 82, 87, 72, 89, 95, 95, 83, 86, 93, 100, 79, 69, 79, 65, 75, 100, 64, 66, 70, 69, 90, 97, 86, 77, 72, 67, 62, 92, 97, 81, 84, 64, 67, 60, 84, 95, 87, 99, 96, 73, 99, 96, 95, 90, 81, 74, 90, 96, 61, 92, 98, 65, 63, 85, 85, 99, 73, 85, 77, 85, 94, 80, 67, 89, 64, 72, 87, 62, 65, 73, 63, 65, 63, 99, 87, 77, 88, 77, 97, 84, 68, 97, 97, 100, 100, 94, 93, 69, 99, 72, 95, 60, 79, 70, 83, 67, 77, 79, 64, 70, 93, 73, 71, 89, 94, 87, 98, 72, 68, 82, 78, 64, 64, 73, 75, 85, 94, 79, 81, 64, 76, 84, 98, 64, 98, 62, 99, 60, 72, 86, 70, 81, 77, 99, 73, 95, 85, 63, 63, 76, 78, 83, 78, 80, 82, 70, 82, 68, 85, 74, 78, 89, 90, 80, 92, 77, 65, 86, 77, 99, 95, 98, 68, 82, 61, 83, 85, 62, 68, 85, 83, 84, 71, 70, 94, 67, 95, 90, 86, 99, 72, 67, 64, 89, 92, 92, 90, 74, 78, 84, 100, 79, 85, 71, 65, 65, 84, 94, 84, 98, 67, 79, 86, 61, 65, 70, 77, 79, 87, 84, 72, 61, 75, 94, 90, 74, 100, 87, 87, 64, 82, 85, 80, 84, 78, 92, 66, 73, 92, 61, 96, 83, 74, 69, 85, 80, 100, 85, 78, 91, 79, 63, 71, 85, 64, 91, 64, 65, 61, 64, 99, 91, 91, 81, 92, 84, 73, 81, 93, 76, 91, 64, 91, 62, 65, 63, 97, 88, 73, 90, 76, 69, 77, 72, 91, 91, 72, 77, 76, 100, 79, 70, 80, 84, 64, 84, 74, 85, 96, 67, 89, 87, 73, 87, 77, 68, 60, 77, 99, 83, 92, 65, 99, 95, 74, 64, 80, 66, 73, 74, 79, 92, 68, 94, 81, 92, 91, 66, 79, 91, 73, 85, 62, 84, 74, 76, 75, 90, 63, 73, 83, 80, 80, 78, 90, 98, 70, 87, 98, 95, 93, 74, 84, 81, 81, 76, 63, 62, 69, 99, 99, 86, 95, 69, 99, 64, 83, 75, 77, 66, 87, 78, 84, 71, 99, 95, 70, 98, 79, 73, 67, 70, 93, 85, 97, 69, 65, 100, 95, 91, 69, 79, 77, 72, 67, 90, 100, 91, 72, 70, 69, 65, 88, 87, 73, 74, 64, 63, 68, 76, 63, 69, 68, 63, 86, 82, 91, 94, 92, 86, 75, 99, 87, 98, 68, 95, 73, 100, 81, 92, 77, 62, 86, 76, 84, 60, 68, 68, 86, 89, 70, 64, 77, 69, 64, 84, 86, 94, 79, 65, 72, 85, 81, 87, 83, 91, 70, 91, 89, 62, 83, 65, 99, 64, 84, 92, 97, 71, 68, 89, 95, 86, 76, 77, 63, 88, 78, 79, 76, 84, 96, 95, 71, 70, 71, 65, 66, 85, 89, 94, 68, 72, 70, 74, 83, 90, 80, 89, 69, 76, 74, 76, 67, 68, 88, 76, 67, 71, 78, 69, 89, 92, 86, 74, 93, 90, 73, 63, 64, 83, 62, 89, 87, 77, 84, 89, 66, 97, 65, 80, 66, 95, 67, 92, 73, 82, 65, 63, 90, 62, 82, 63, 96, 96, 72, 73, 85, 84, 90, 87, 67, 96, 70, 64, 65, 67, 62, 95, 69, 66, 77, 85, 82, 72, 89, 84, 75, 79, 67, 79, 87, 96, 65, 92, 67, 92, 77, 98, 87, 77, 82, 62, 88, 62, 93, 93, 69, 73, 79, 84, 84, 60, 92, 98, 77, 81, 66, 82, 97, 68, 91, 61, 64, 74, 77, 72, 86, 97, 76, 68, 94, 83, 78, 66, 71, 98, 95, 63, 81, 69, 76, 95, 81, 79, 73, 98, 81, 76, 91, 74, 67, 83, 87, 89, 95, 63, 98, 87, 82, 90, 92, 82, 74, 72, 98, 81, 99, 75, 80, 95, 95, 94, 95, 83, 82, 99, 80, 76, 95, 77, 77, 74, 81, 85, 92, 93, 81, 86, 89, 82, 67, 71, 71, 81, 95, 78, 85, 72, 77, 88, 99, 96, 100, 61, 68, 77, 85, 70, 80, 97, 93, 99, 62, 61, 80, 74, 96, 98, 60, 79, 96, 64, 75, 98, 75, 99, 75, 60, 88, 99, 66, 83, 98, 86, 82, 77, 99, 87, 82, 62, 68, 67, 70, 72, 74, 77, 64, 87, 81, 93, 86, 98, 94, 77, 67, 82, 81, 100, 62, 83, 71, 71, 92, 72, 82, 97, 76, 94, 98, 86, 94, 98, 71, 79, 88, 69, 60, 74, 88, 74, 96, 100, 73, 78, 68, 72, 68, 91, 89, 85, 75, 96, 99, 67, 64, 77, 83, 81, 73, 82, 68, 86, 82, 64, 61, 67, 83, 88, 68, 85, 76, 86, 100, 98, 64, 89, 98, 89, 90, 71, 60, 67, 65, 97, 66, 82, 82, 62, 82, 88, 81, 77, 94, 89, 90, 77, 72, 79, 64, 67, 80, 94, 69, 94, 63, 82, 94, 80, 60, 82, 93, 85, 94, 66, 67, 97, 61, 73, 87, 74, 77, 78, 69, 89, 64, 71, 62, 77, 87, 99, 98, 69, 64, 66, 88, 89, 87, 73, 67, 79, 71, 67, 90, 83, 98, 61, 90, 98, 94, 67, 73, 67, 82, 77, 63, 69, 82, 95, 76, 69, 82, 60, 73, 69, 99, 89, 74, 64, 93, 85, 82, 97, 81, 72, 85, 80, 64, 79, 87, 78, 62, 73, 72, 80, 95, 77, 72, 76, 74, 93, 62, 72, 87, 68, 70, 95, 86, 61, 100, 95, 70, 75, 85, 79, 94, 70, 61, 78, 96, 99, 91, 66, 77, 72, 84, 67, 63, 73, 69, 62, 67, 79, 100, 75, 79, 71, 74, 86, 95, 61, 66, 97, 78, 98, 95, 90, 97, 69, 93, 95, 74, 91, 73, 64, 72, 81, 73, 91, 77, 75, 90, 90, 96, 76, 68, 91, 67, 77, 100, 71, 67, 90, 86, 83, 69, 78, 66, 70, 79, 61, 87, 77, 95, 88, 60, 85, 81, 69, 78, 71, 88, 75, 97, 75, 67, 97, 92, 73, 84, 80, 98, 90, 79, 70, 76, 70, 94, 82, 93, 71, 82, 63, 97, 76, 78, 70, 79, 95, 96, 69, 87, 82, 94, 64, 82, 92, 90, 64, 81, 74, 76, 77, 69, 78, 98, 66, 61, 97, 79, 99, 87, 66, 68, 91, 67, 69, 69, 95, 78, 76, 82, 62, 79, 80, 61, 66, 75, 69, 82, 65, 61, 61, 79, 72, 78, 62, 96, 100, 66, 86, 85, 88, 81, 86, 86, 89, 86, 87, 70, 60, 99, 76, 68, 91, 70, 84, 88, 96, 94, 67, 64, 71, 75, 96, 98, 94, 67, 99, 72, 80, 91, 85, 98, 65, 98, 88, 80, 79, 64, 70, 99, 66, 68, 68, 91, 73, 63, 69, 100, 68, 74, 73, 89, 67, 96, 67, 95, 71, 86, 86, 64, 73, 69, 71, 70, 68, 83, 93, 61, 79, 62, 99, 92, 63, 84, 90, 68, 93, 92, 95, 98, 76, 92, 100, 74, 71, 70, 69, 63, 90, 88, 70, 95, 83, 96, 96, 99, 79, 76, 72, 73, 67, 70, 86, 65, 67, 70, 99, 84, 70, 79, 65, 88, 100, 76, 85, 93, 89, 65, 80, 66, 66, 83, 99, 64, 71, 95, 63, 81, 76, 72, 72, 95, 89, 87, 92, 70, 78, 72, 86, 76, 81, 87, 98, 86, 70, 97, 87, 91, 72, 97, 82, 88, 84, 65, 70, 93, 85, 94, 94, 69, 83, 96, 90, 97, 70, 66, 82, 67, 62, 61, 84, 74, 96, 85, 87, 91, 66, 68, 70, 97, 63, 77, 96, 90, 99, 91, 99, 88, 86, 71, 83, 97, 91, 89, 82, 92, 68, 84, 73, 68, 65, 70, 71, 75, 71, 65, 64, 63, 94, 80, 90, 63, 79, 92, 84, 80, 99, 96, 70, 91, 61, 99, 61, 63, 77, 96, 70, 83, 91, 72, 76, 65, 61, 66, 74, 63, 61, 86, 75, 87, 69, 94, 80, 91, 81, 79, 90, 99, 92, 68, 82, 67, 74, 97, 66, 85, 84, 65, 73, 83, 67, 99, 69, 61, 82, 88, 89, 88, 89, 72, 91, 72, 83, 70, 64, 93, 67, 71, 74, 63, 86, 86, 87, 89, 88, 65, 86, 71, 61, 77, 77, 83, 74, 88, 81, 80, 85, 72, 66, 66, 76, 67, 90, 93, 84, 94, 89, 63, 80, 72, 74, 91, 97, 95, 63, 70, 73, 74, 78, 77, 93, 63, 66, 91, 89, 96, 92, 93, 86, 78, 95, 61, 62, 98, 71, 76, 63, 70, 88, 99, 81, 60, 60, 64, 64, 68, 96, 99, 92, 96, 94, 77, 64, 77, 100, 64, 93, 93, 97, 98, 66, 79, 89, 68, 62, 96, 80, 67, 74, 67, 92, 96, 88, 88, 94, 91, 91, 61, 69, 91, 90, 86, 63, 66, 67, 76, 86, 89, 65, 63, 66, 61, 85, 99, 75, 72, 66, 66, 65, 75, 73, 67, 66, 77, 78, 71, 64, 99, 95, 98, 86, 79, 91, 98, 91, 88, 90, 93, 72, 97, 72, 93, 93, 86, 75, 60, 93, 63, 80, 97, 61, 91, 62, 77, 63, 81, 62, 85, 92, 92, 69, 85, 89, 68, 98, 82, 64, 91, 88, 62, 82, 64, 100, 61, 97, 74, 66, 93, 74, 76, 96, 80, 82, 95, 79, 99, 75, 75, 68, 90, 99, 91, 62, 99, 74, 72, 96, 83, 69, 100, 63, 81, 99, 70, 82, 63, 76, 62, 68, 95, 90, 89, 76, 91, 78, 74, 90, 96, 62, 61, 95, 74, 97, 85, 90, 69, 76, 67, 77, 98, 80, 74, 93, 99, 62, 91, 66, 84, 73, 67, 84, 83, 86, 90, 94, 70, 80, 86, 62, 89, 79, 78, 66, 99, 76, 98, 81, 94, 73, 99, 81, 66, 69, 79, 62, 77, 91, 74, 99, 84, 93, 82, 97, 100, 76, 70, 64, 71, 91, 81, 88, 75, 80, 96, 74, 96, 79, 86, 95, 91, 68, 84, 67, 71, 76, 81, 91, 90, 91, 73, 95, 85, 93, 82, 69, 82, 88, 79, 87, 99, 73, 81, 65, 86, 76, 95, 64, 92, 91, 81, 61, 89, 92, 67, 74, 98, 75, 93, 68, 92, 86, 75, 86, 100, 83, 62, 76, 82, 72, 81, 65, 68, 64, 70, 97, 94, 81, 99, 65, 66, 87, 61, 62, 96, 92, 77, 78, 82, 64, 70, 68, 81, 78, 91, 81, 84, 89, 61, 61, 76, 74, 78, 99, 63, 81, 90, 71, 61, 79, 96, 98, 95, 78, 63, 78, 87, 93, 72, 67, 98, 63, 93, 87, 99, 79, 80, 84, 78, 75, 81, 73, 60, 72, 65, 80, 88, 85, 92, 81, 92, 77, 88, 77, 90, 67, 69, 69, 91, 84, 76, 80, 87, 94, 71, 65, 88, 89, 77, 65, 77, 68, 77, 75, 90, 91, 84, 93, 83, 97, 79, 92, 63, 81, 60, 63, 68, 92, 78, 61, 63, 70, 82, 84, 65, 91, 75, 89, 96, 81, 80, 71, 78, 77, 65, 80, 63, 91, 68, 74, 66, 100, 62, 78, 78, 72, 83, 91, 84, 89, 96, 93, 80, 91, 64, 75, 77, 84, 100, 80, 68, 82, 82, 68, 88, 74, 100, 90, 92, 67]

In [21]:
employee_df = pd.read_csv("Employee.csv")
employee_df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [22]:
employee_df.info()
employee_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [24]:
print(employee_df.columns)

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [25]:
print("Mean Age:", employee_df["Age"].mean())
print("Median Age:", employee_df["Age"].median())
print("Mode Age:", employee_df["Age"].mode())
print("Standard Deviation of Age:", employee_df["Age"].std())
print("Minimum Age:", employee_df["Age"].min())
print("Maximum Age:", employee_df["Age"].max())

Mean Age: 29.393294648613796
Median Age: 28.0
Mode Age: 0    26
Name: Age, dtype: int64
Standard Deviation of Age: 4.826087009126047
Minimum Age: 22
Maximum Age: 41

In [27]:
print("Standard Deviation of Age:", employee_df["Age"].std())

Standard Deviation of Age: 4.826087009126047

In [28]:
print("Maximum Age:", employee_df["Age"].max())
print("Minimum Age:", employee_df["Age"].min())

Maximum Age: 41
Minimum Age: 22

In [29]:
age_array = np.array(employee_df["Age"])
print("Maximum Age:", max(age_array))
print("Minimum Age:", min(age_array))

Maximum Age: 41
Minimum Age: 22

In [32]:
employee_df['EverBenched'] = employee_df['EverBenched'].replace({'Yes': 1, 'No': 0})
employee_df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,0,0,0
1,Bachelors,2013,Pune,1,28,Female,0,3,1
2,Bachelors,2014,New Delhi,3,38,Female,0,2,0
3,Masters,2016,Bangalore,3,27,Male,0,5,1
4,Masters,2017,Pune,3,24,Male,1,2,1

In [33]:
employee_df.describe()

,JoiningYear,PaymentTier,Age,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,0.102729,2.905652,0.343864
std,1.863377,0.561435,4.826087,0.303638,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,0.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,0.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,0.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,1.000000,7.000000,1.000000